# numpy向量计算

In [6]:
import dis
import numpy as np

a=np.array([3,2,1])
b=np.array([1,2,3])
# 向量加
display(a+b)
# 向量乘以常量
display(a*3)
# 向量单纯的乘法
display(a*b)
# 点乘
display(a.dot(b))
# 取模
display(np.linalg.norm(a))
# 单位向量
display(a/np.linalg.norm(a))

array([4, 4, 4])

array([9, 6, 3])

array([3, 4, 3])

10

3.7416573867739413

array([0.80178373, 0.53452248, 0.26726124])